import Head from 'next/head'
export default function Header() {
    return (
        <>
            <Head>
                <title>Akhlaq Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='main-header'>
                <div>
                    Akhlaq Chat
                </div>
            </div>
        </>
    )
}